[build]
functions = "netlify/functions"
command = "npm run build"
publish = ".next"


[[redirects]]
  from = "/api/gifts"
  to = "/.netlify/functions/gifts"
  status = 200

  
[build.environment]
NODE_VERSION = "18"

[[plugins]]
package = "@netlify/plugin-nextjs"
